"project_id" : "417706"
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
 {
  "source" : "/messages/en.json",
  "translation" : "/messages/%locale%.json",
  "type" : "json",
 }
]